# Generated by Django 4.0 on 2022-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150)),
                ('class_subject', models.CharField(max_length=10)),
                ('catalog_number', models.CharField(max_length=10)),
            ],
        ),
    ]
