# Generated by Django 4.0 on 2022-10-24 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_subject',
            new_name='department',
        ),
        migrations.AddField(
            model_name='class',
            name='component',
            field=models.CharField(default='N/A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='days',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.CharField(default='N/A', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.CharField(default='N/A', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.CharField(default='N/A', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.CharField(default='N/A', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to='auth.user'),
        ),
    ]
