# Generated by Django 4.0 on 2022-10-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_class_subject_class_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_setup',
            field=models.BooleanField(default=False),
        ),
    ]
