# Generated by Django 4.0 on 2022-10-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_account_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
    ]
