# Generated by Django 4.0 on 2022-11-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_preferences_profile_prefrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='cramming',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='favorite_location',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='in_person',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='quiet_study',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='quizzing',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='revision',
        ),
        migrations.AddField(
            model_name='profile',
            name='cramming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_location',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='in_person',
            field=models.BooleanField(default=True),
        ),
    ]
