# Generated by Django 4.0 on 2022-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_profile_prefrences_delete_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_setup',
            new_name='classesSet',
        ),
        migrations.AddField(
            model_name='profile',
            name='preferencesSet',
            field=models.BooleanField(default=False),
        ),
    ]
