# Generated by Django 4.0 on 2022-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_account_setup_profile_classesset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_location',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
    ]
