# Generated by Django 4.0.8 on 2022-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_profile_favorite_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_you',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bioSet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.TextField(default='Not Specified', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.TextField(default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.TextField(default='Not Specified', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_location',
            field=models.TextField(default='Not Specified', max_length=20),
        ),
    ]
