# Generated by Django 4.0.8 on 2022-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_profile_bio_profile_about_you_profile_bioset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.TextField(default='Not Specified', max_length=100),
        ),
    ]
