# Generated by Django 4.0.8 on 2022-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_profile_friend_alter_profile_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.TextField(default='Not Specified', max_length=10),
        ),
    ]
