# Generated by Django 4.0.8 on 2022-11-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_friends_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friend',
        ),
    ]
