# Generated by Django 4.0 on 2022-11-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_profile_friendslist_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.TextField(default='Not Specified', max_length=50),
        ),
    ]
