# Generated by Django 4.0 on 2022-11-07 17:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_studysession_remove_profile_friends_delete_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='description',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studysession',
            name='location',
            field=models.TextField(default='Remote', max_length=150),
        ),
        migrations.AddField(
            model_name='studysession',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
