# Generated by Django 4.0 on 2022-11-07 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_studysession_creator_studysession_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='home.Profile'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='title',
            field=models.TextField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studysession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='home.profile'),
        ),
    ]
