# Generated by Django 4.0 on 2022-11-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_studysession_attendees_studysession_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='creator',
            new_name='organizer',
        ),
    ]
