# Generated by Django 4.0.8 on 2022-11-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_rename_creator_studysession_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Remote', max_length=150)),
                ('date', models.TextField(default='Remote', max_length=150)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='home.profile')),
            ],
        ),
        migrations.AddField(
            model_name='studysession',
            name='messagess',
            field=models.ManyToManyField(blank=True, to='home.discussionboard'),
        ),
    ]
