# Generated by Django 4.0 on 2022-11-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_message_remove_studysession_messagess_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='', max_length=150),
        ),
    ]
