# Generated by Django 4.0.8 on 2022-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_message_date_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inactiveClasses',
            field=models.ManyToManyField(blank=True, related_name='inactiveClasses', to='home.class'),
        ),
    ]
