# Generated by Django 4.0.8 on 2022-12-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile_inactiveclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nameSet',
            field=models.BooleanField(default=False),
        ),
    ]
